export const CREATE_ORDER_REQUEST= "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS= "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL= "CREATE_ORDER_FAIL";

export const MY_ORDER_REQUEST= "MY_ORDER_REQUEST";
export const MY_ORDER_SUCCESS= "MY_ORDER_SUCCESS";
export const MY_ORDER_FAIL= "MY_ORDER_FAIL";

export const ORDER_DETAIL_REQUEST= "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_SUCCESS= "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAIL_FAIL= "ORDER_DETAIL_FAIL";

export const CLEAR_ERRORS= "CLEAR_ERRORS";

export const CREATE_PAYMENT_REQUEST= "CREATE_PAYMENT_REQUEST";
export const CREATE_PAYMENT_SUCCESS= "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAIL= "CREATE_PAYMENT_FAIL";
